#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-recursive-crawl
Version  : 0.2.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/c3/f8/93df7ed8fb24c59b1550fdc19f13284b0a89ae01703f45ce516c0a3717dd/colcon-recursive-crawl-0.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c3/f8/93df7ed8fb24c59b1550fdc19f13284b0a89ae01703f45ce516c0a3717dd/colcon-recursive-crawl-0.2.0.tar.gz
Summary  : Extension for colcon to recursively crawl for packages.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-recursive-crawl-python3
Requires: colcon-recursive-crawl-python
Requires: colcon-core
BuildRequires : buildreq-distutils3

%description
======================

%package python
Summary: python components for the colcon-recursive-crawl package.
Group: Default
Requires: colcon-recursive-crawl-python3

%description python
python components for the colcon-recursive-crawl package.


%package python3
Summary: python3 components for the colcon-recursive-crawl package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-recursive-crawl package.


%prep
%setup -q -n colcon-recursive-crawl-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533002997
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
