#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-recursive-crawl
Version  : 0.2.1
Release  : 13
URL      : https://files.pythonhosted.org/packages/c3/9e/bc1935dc532af90b802ed16cf0a1f5f858275e49d775895fca5161fc9910/colcon-recursive-crawl-0.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c3/9e/bc1935dc532af90b802ed16cf0a1f5f858275e49d775895fca5161fc9910/colcon-recursive-crawl-0.2.1.tar.gz
Summary  : Extension for colcon to recursively crawl for packages.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-recursive-crawl-python = %{version}-%{release}
Requires: colcon-recursive-crawl-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3
BuildRequires : colcon-core

%description
======================

%package python
Summary: python components for the colcon-recursive-crawl package.
Group: Default
Requires: colcon-recursive-crawl-python3 = %{version}-%{release}

%description python
python components for the colcon-recursive-crawl package.


%package python3
Summary: python3 components for the colcon-recursive-crawl package.
Group: Default
Requires: python3-core
Provides: pypi(colcon_recursive_crawl)
Requires: pypi(colcon_core)

%description python3
python3 components for the colcon-recursive-crawl package.


%prep
%setup -q -n colcon-recursive-crawl-0.2.1
cd %{_builddir}/colcon-recursive-crawl-0.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583528721
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
